# application.yml

spring:
  profiles:
    active: dev
  application:
    name: simple-deployment
  datasource:
    url: jdbc:mysql://47.101.223.234:3306/userdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

simple:
  common:
    sentry-dsn: ${SENTRY_DSN:https://21cb9790be1545f195743a18c77f37d8@o461905.ingest.sentry.io/5464621}
server:
  port: 80
  servlet:
    context-path: /accountcenter